# {{ site.myvariable }}.
title: Desafio de Programação
author: Lucas H. Negri
email: lucas.negri@ifms.edu.br
description: >- 
  Sítio que reúne informações sobre o projeto de ensino "Desafio de Programação", realizado no
  Instituto Federal de Mato Grosso do Sul, câmpus Nova Andradina. Aqui você encontrará informações
  sobre as edições passadas e exemplos de código relevantes para competições como a Olimpíada Brasileira
  de Informática e a Maratona de Programação
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://desafio-ifms.web.app"

# Build settings
markdown: kramdown
theme: tale
plugins:
  - jekyll-feed

permalink: /:year-:month-:day/:title
paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
