 version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:lts
      steps:
        - checkout
        - run: npm install -g firebase-tools
        - run: bundle exec jekyll build --verbose
        - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
